export const data = [
    {
        id: 1,
        name: 'Grocery Application',
        skills: ['React Native', 'Typescript', 'Redux'],
        points: [
            'Responsible for Design and development of User as well as Delivery partner Application',
            'Added family grouping functionality',
            'Integrated Promo-code based payment',
            'Integrated RazorPay for payment facilitation',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'Catalog Application',
        skills: ['Next.js', 'React', 'redux', 'React Native'],
        points: [
            'Worked with a team to develop a mobile application, storing and showing details of products',
            'Responsive with core ui components',
            'Incorporated zoom SDK for video call with customers',
            'developed a mobile-ready website with responsive UI.',
            'Integrated MirrAr web plug-in to view products on the go.',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'E-commerce sweets selling website',
        skills: ['Next.js', 'React', 'redux'],
        points: [
            'Worked with a team to develop a web and a mobile application for an e-commerce platform.',
            'List products with details (price and manufacture) for users to choose from.',
            'integrated different payment method handles gift card and personal message',
            'Responsible for bug fixes and adding new modules in the web',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'BLE Connector',
        skills: ['React Native'],
        points: [
            'Design and development of a BLE Mobile Application, reverse engineering a current webBLE product',
            'Integrated BLE-Manger package for connection',
            'Send and receive response of connected device',
            'Handled multiple events with log',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'Online Documents Storage',
        skills: ['React', 'Ionic'],
        points: [
            'Bug fixes and new modules and functionality.',
            'Created Android and iOS application from react code using ionic capacitor',
            'Handles permission and other challenges with that',
            'Used Global context for all file and folder',
            'Share with other user and share link integrated',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'Rewards-Driven Application',
        skills: ['React Native', 'Redux'],
        points: [
            'Independently developed Front end of mobile application that took care guiding visitors for best places to travel at a location',
            'Accommodated use of coupon validation and applying coupons on different sites of visit',
            'Designed a chatbot for facilitating users to have an instant reply from the system',
            'Added multilingual support with i18n package',
            'Migration from MobX to Redux',
            'The users of the system are end customers and vendors',
        ],
        isOpen: false,
    },
    {
        id: 1,
        name: 'Online Menu',
        skills: ['Next.js', 'React'],
        points: [
            'Responsible for design and development of full Application',
            'Dynamic Menu based on URL',
            'Meta Tags for each Products',
            'Handled Dynamic Categories and SubCategories',
        ],
        isOpen: false,
    },
]
